### ISSUE TITLE
ERROR: string indices must be integers, not unicode

### ISSUE THREAD

**Issue by i0bound** [Julian/jsonschema#574] opened 2019-06-27 15:23 UTC
Great library, I've used it for a few simpler schema's, thanks!,  

Unfortunately it choked unexpectedly on the attached schema. I have attached the schema (pns_firmware_A - from Brother International Corporation) along with a sample Python script (validate.py) and the json that I was trying to validate (Setting.json). The error returned is: "ERROR: string indices must be integers, not unicode".

The sample json validates with the Brother schema with no problems using https://www.jsonschemavalidator.net/

Note: I had to add a txt extension to drag and drop the following files:

[pns_firmware_A.py.txt](https://github.com/Julian/jsonschema/files/3335417/pns_firmware_A.py.txt)

[Setting.json.txt](https://github.com/Julian/jsonschema/files/3335409/Setting.json.txt)

[validate.py.txt](https://github.com/Julian/jsonschema/files/3335430/validate.py.txt)

**Comment by Julian** [comment] 2019-06-29 18:02
Hi. Happy to have a look, but please work on creating a [short, self contained example](http://sscce.org/). In general when doing so it's clear (both to me *and* you :) what the issue is.

> The sample json validates with the Brother schema with no problems using https://www.jsonschemavalidator.net/

The online JSON Schema validators are in my experience quite buggy :), so I wouldn't take this to mean much.

Closing for now, but happy to have a look if you can provide a short runnable example.

**Comment by Julian** [comment] 2019-06-29 18:02
And of course glad to hear it's been useful to you!

**Closed by Julian** 2019-06-29 18:02 UTC
