### ISSUE TITLE
Better documentation on extending RefResolver

### ISSUE THREAD

**Issue by foxx** [Julian/jsonschema#225] opened 2015-05-10 13:55 UTC
The documentation made it quite difficult to understand how `RefResolver` should be extended, and I had to trawl through code to make it work. This is useful when you want to reference other schemas, but you don't want to use `file://`

It would be nice to see better documentation on this, but in the mean time, here is how I got it working for anyone who runs into the same problem;

```py
import jsonschema

class SchemaResolver(jsonschema.RefResolver):
    def resolve_remote(self, uri):
        if uri.startswith('/SOMETHING'):
            # your custom schema goes here
            return {}
        else:
            # fallback to original
            return super(SchemaResolver, self).resolve_remote(uri)

def validate(schema, doc):
    """Validate using custom resolver"""
    resolver = SchemaResolver.from_schema(schema)
    validator_cls = jsonschema.validators.validator_for(schema)
    validator_cls.check_schema(schema)
    validator = validator_cls(schema, resolver=resolver)
    validator.validate(doc)

schema = {"$ref": "/SOMETHING/v1/definitions.json"}
doc = {"field": "value"}

validate(schema, doc)
```

**Comment by Julian** [comment] 2015-05-10 14:04
Hey!

This is a duplicate of #135, but yes you're certainly right, documentation would be great here, would be awesome if you could write up what you've found possibly?

For your specific solution, `jsonschema` doesn't encourage (or explicitly support) inheritance for `RefResolver` (or really any of its APIs) -- I suspect you'll find other "solutions" for relative file references in that issue ticket, but it's certainly something that comes up enough to warrant some more direction.

Thanks!

**Closed by Julian** 2015-05-10 14:04 UTC

**Comment by foxx** [comment] 2015-05-10 14:08
Thanks for the quick reply, sorry I didn't see #135 previously. I'll have a read through and leave my thoughts, thanks again :)

**Comment by foxx** [comment] 2015-05-10 15:17
I was able to find an alternative way to support this on `2.4.0` without needing to subclass. Either works fine, admittedly you have more customisation control if you subclass, but this is more readable and forces you to use correctly formed URIs

```
#!/usr/bin/env python

import jsonschema
import json

rootschema = json.load(open('./rootschema.json', 'r'))
schema = json.load(open('./schema.json', 'r'))
doc = json.load(open('./doc.json', 'r'))

validator_cls = jsonschema.validators.validator_for(schema)
validator_cls.check_schema(schema)
validator = validator_cls(schema)

validator.resolver.store['/v1/rootschema.json'] = rootschema
validator.validate(doc)
```

**Comment by ksolie** [comment] 2023-09-22 15:12
@foxx Were you able to find a solution using `Registry`?
