### ISSUE TITLE
JSON Schema does not validate "None" as null

### ISSUE THREAD

**Issue by sogo-dowole** [Julian/jsonschema#826] opened 2021-07-17 04:20 UTC
After specifying "null" as expected type in my schema, when a null field is sent over to my app, python converts it to "None" but jsonSchema does not convert it back to null before checking, hence validation always fails

**Comment by Julian** [comment] 2021-07-17 04:47
Hello. Please include your code to reproduce.

**Comment by Julian** [comment] 2021-07-19 10:00
Happy to look at this if there's a bug and you share code. Closing for now.

**Closed by Julian** 2021-07-19 10:00 UTC

**Comment by ajrice6713** [comment] 2022-11-04 00:00
@Julian I am also seeing this issue: 

```
None is not of type 'integer'

Failed validating 'type' in
schema['properties']['messages']['items']['properties']['messageSize']:
    {'description': 'The size of the message including message content and '
                    'headers.',
     'example': 27,
     'nullable': True,
     'type': 'integer'}

On instance['messages'][0]['messageSize']:
    None
```

The JSON Object I am passing in as `instance` 
```json
  {
    "messageId": "1667511578121nqxo5oqmjzaowag2",
    "accountId": "9900778",
    "sourceTn": "+19194248243",
    "destinationTn": "+19198021884",
    "messageStatus": "DELIVERED",
    "messageDirection": "OUTBOUND",
    "messageType": "sms",
    "segmentCount": 1,
    "messageLength": 13,
    "messageSize": null,
    "attachmentCount": null,
    "recipientCount": null,
    "errorCode": 0,
    "carrierName": "Verizon",
    "campaignClass": null,
    "receiveTime": "2022-11-03T21:39:38.305Z"
  }
```

And the Schema from my openapi spec 

```yml
  messageSize:
    type: integer
    description: The size of the message including message content and headers.
    nullable: true
    example: 27
```

**Comment by Julian** [comment] 2022-11-04 00:05
Hi. Your schema says `messageSize` is `type: integer`, and the error's saying `None` isn't an integer, which it isn't -- what behavior are you expecting?

**Comment by Julian** [comment] 2022-11-04 00:18
Oh (seeing this in a browser now) -- are you expecting `nullable` to do something? That's not a keyword in JSON Schema.

**Comment by ajrice6713** [comment] 2022-11-04 12:21
@Julian I see - `nullable` is an OpenAPI construct - it looks like JSON Schema supports something like `"type": ["int", "null"]` - Im using this to validate REST API responses against the provided API specification - i overlooked the fact that this isn't API Specific - so it makes sense that your library wouldn't support `nullable`.

I will have to look at my options - I don't expect support for an OpenAPI specific construct to be added into this library - but thank you for the clarity and fast response!
