### ISSUE TITLE
Python 2.7 support broken with latest pyrsistent release

### ISSUE THREAD

**Issue by evandentid** [Julian/jsonschema#733] opened 2020-09-09 14:57 UTC
pyrsistent release 0.17.0 no longer supports py2

https://github.com/tobgu/pyrsistent/blob/master/CHANGES.txt#L10-L14

Version set here: https://github.com/Julian/jsonschema/blob/master/setup.cfg#L31

**Comment by Julian** [comment] 2020-09-09 15:02
Hi, this is a dupe of #732 

Have a look at the upstream ticket there in pyrsistent which is where the fix should go.

**Closed by Julian** 2020-09-09 15:02 UTC
