### ISSUE TITLE
Ensure jsonschema's extension mechanisms support enough for implementing $data as an end user

### ISSUE THREAD

**Issue by naquad** [Julian/jsonschema#560] opened 2019-05-15 14:32 UTC
[$data proposal](https://github.com/json-schema-org/json-schema-spec/issues/51) implemented by [AJV](https://github.com/epoberezkin/ajv) allows validation based on another value. It can drastically reduce the amount of custom coded performed after the schema has been validated.

Additionally, interoperability with AJV would allow to quickly implement UIs with AJV-based form generators such as [VueFormJsonSchema](https://github.com/jarvelov/vue-form-json-schema) or similar solutions.

**Comment by Julian** [comment] 2019-05-15 14:51
Hi.

Thanks for the ticket -- in general, this library only implements what is present in specifications.

It's fairly easy to implement whatever other support you need or want on top either in a higher level library or within your own specific project, but yeah here, if it's not in a spec it generally wouldn't go in.

**Comment by naquad** [comment] 2019-05-15 15:12
Hi.

I've tried to implement this feature on a higher level or extended validators but caught myself rewriting all validators to support resolution of validator argument. A try to apply `RefResolver` has failed as it doesn't work with random data rather schemas only.

**Comment by Julian** [comment] 2019-05-15 15:18
So, certainly interested in things more like that. If there are specific things that you ran into while trying to implement it that were difficult, talking about what lower-level things you'd want to see is definitely in-scope.

Ideally with examples of what you implemented, so we could see what the pain points were.

**Comment by naquad** [comment] 2019-05-15 15:57
My first approach was to replace all `{"$data": ...}`

**Comment by naquad** [comment] 2019-05-15 16:07
My first approach was to extract `{"$data": ...}` values and apply them later. That's the point where I've started rewriting validators in my own code.

The second approach was to turn off schema validation (yes, not good) and then hack `iter_errors` as that's the point where `$data` can be resolved:

```
        def iter_errors(self, instance, _schema=None):
            if _schema is None:
                _schema = self.schema

            scope = _schema.get(u"id")
            if scope:
                self.resolver.push_scope(scope)
            try:
                ref = _schema.get(u"$ref")
                if ref is not None:
                    validators = [(u"$ref", ref)]
                else:
                    validators = iteritems(_schema)

                for k, v in validators:
                    validator = self.VALIDATORS.get(k)
                    if validator is None:
                        continue

                    # TODO: handle $data in v here
                    errors = validator(self, v, instance, _schema) or ()
                    for error in errors:
                        # set details if not already set by the called fn
                        error._set(
                            validator=k,
                            validator_value=v,
                            instance=instance,
                            schema=_schema,
                        )
                        if k != u"$ref":
                            error.schema_path.appendleft(k)
                        yield error
            finally:
                if scope:
                    self.resolver.pop_scope()
```

But as you can see there's nothing to hook into and it'll be a copy-paste implementation. To efficiently implement this the following needs to happen:
1. Schema update. As `$data` is not supported by current schema specs.
2. Handle `$data` in the `iter_error` loop somehow. As `RefResolver` is schema-based this will have to be implemented as a separate class that can track the current position in data rather than schema and be able to return value at the requested path.

And I'm not sure if I'm right here as it seems to be too much work for a simple feature so please correct me if I'm wrong.

**Comment by handrews** [comment] 2019-05-16 15:34
@naquad `$data` is controversial and has never achieved a level of support that outweighs the problems.  There is an issue label for it in the spec repo if you want to take a look.  While people occasionally express interest no one has stepped up who can see it through as a specification project, so it's unlikely to be added anytime soon.  And may be better left as an extension anyway.  Either way, it's a spec repo question.

**Comment by Julian** [comment] 2019-05-16 15:41
@naquad the way to extend validators is with the [validator extension API](https://python-jsonschema.readthedocs.io/en/stable/creating/#jsonschema.validators.extend) -- I can't tell -- have you found that, and tried it?

Modifying `iter_errors` is indeed not supported.

The question to me is given the existing API whether one would be able to implement `$data` (or something like it) on top in their own project.

**Comment by naquad** [comment] 2019-05-16 19:31
@handrews I've looked through the referenced $data spec proposal. Leaving aside "schema" concept and if document content should be a part of the schema (that is should domain-specific constraints influence document structure validity as $data makes document validity to depend also on content rather than just pure structure) this proposal solves a lot of tasks at hand when one tries to use JSON schema as metadata solution for all application parts. So from the practical point of view, it is a must and that's why AJV which is a very robust practical thing has implemented it. Using $data reduces the amount of hand-written validations, simplifies error generation and handling. On a high level one can say that this thing is one of the vital pieces to make JSON schema represent not just some document structure, but data model. To some extent of course.

@Julian anything I can do outside of `iter_error` is an ugly hack as `iter_error` is responsible not only for the validator invocation but also for path tracking. This is basically the primary loop of the whole validation process. Referenced custom validation would make sense if I would like to roll out something like `dynamicMinimum`, `dynamicMaximum`, etc... validators, but I'm not as validators are fine, their logic (and code) should stay the same. The value itself should be preprocessed. And schema should be updated of course.

**Comment by Julian** [comment] 2019-05-16 23:29
> @Julian anything I can do outside of iter_error is an ugly hack as iter_error is responsible not only for the validator invocation but also for path tracking. 

It's not an ugly hack, it's the current public API :) -- it might be deficient though, which is what I'd love to figure out -- but it does not do path tracking, it just does *default* path tracking if you don't already do so yourself, if I understand what you mean there.

Sounds like to be more helpful I need to understand what `$data` is meant to do, so I can see whether it's implementable given the current API. But yeah, there are 2 current ways to extend the specifications -- one is to do pre-transformations. This one is completely outside of the library, you can do whatever transformations you want before handing a schema ultimately to a validator, and you can obviously package that transformation up into a helper method. The other way is via `jsonschema.validators.extend`.

It's totally possible that some wildly different validator might need even deeper changes (heck, a bunch from draft 6 required redesigning significant pieces of the library), but I can tell you one thing, which is overriding `iter_errors` itself will not be it :)

**Comment by handrews** [comment] 2019-05-18 06:43
@naquad please take the "should `$data` be in the spec" topic to the spec repo.

The primary problem on the spec side is that no one has volunteered to resolve all of the concerns and see it through.  Having a volunteer does not guarantee that it will be accepted, but it is a necessary first step.  You will also find that not everyone views JSON Schema as the right starting point for a data model, or if it is how far it should go to support that in the standard.  This would be one of the many things that needs resolving.

**Comment by threewordphrase** [comment] 2019-12-14 20:04
Hi, I'm working on something that needs $data like handling. If the top-level object were passed down to the customer validator this would be quite easy to implement if the root instance and, optionally root schema were passed down to the validator functions:

**Comment by threewordphrase** [comment] 2019-12-14 20:10
Hi, I'm working on something that needs $data like handling. If the top-level object were passed down to the customer validator this would be quite easy to implement if the root instance and, optionally root schema, were passed down to the validator functions. AJV (for javascript) does this. Say my objective is a schema that validates that 2 attributes equal each other:

```python
schema = {
    "type" : "object",
    "properties" : {
        "price" : { "type" : "number" },
        "name_dupe" : {"type" : "string"},
        "name" : {
            "type" : "string",
            'equalsRef': {
                '$data': '1/name_dupe'
                }
            },
    },
}

instance = {
        'name': 'eggs',
        'name_dupe': 'not eggs',
        'price': 1234.99
        }

def equalsRefValidator(validator, value, instance, schema, root_instance, root_schema):
    # here I can use the $data attribute of maximum to introspect root_data
    # and write whatever I want.
    # value = {'$data': '1/name_dupe'}
    # instance = 'eggs'
    # schema = {'type': 'string', 'equalsRef': {'$data': '1/name_dupe'}}
    # root_instance = { 'name': 'eggs',  'name_dupe': 'not eggs', 'price': 1234.99 }
    pass

custom_validators = {
        u'equalsRef': equalsRefValidator
        }

CustomValidator = extend(
            Draft7Validator,
            validators=custom_validators)
```

Passing root_instance down to the validator function would allow me to easily implement $data like handling on my own without major changes to this codebase.

**Comment by Julian** [comment] 2019-12-14 21:08
The root schema is already available, it's `validator.schema`.

The instance.. yeah doesn't occur to me immediately, there may still be a way to have it passed to you, but if not, then yeah that seems reasonable to add, but couldn't be done the way you have it there, since that'd be backwards incompatible, so we'd need another way.

Possibly introducing a `RunningValidator` that represents a validator that's in the middle of validating an instance but otherwise satisfies `iValidator`, and then replacing the `validator` parameter with one of those.

**Comment by threewordphrase** [comment] 2019-12-14 21:11
Would it be backwards incompatible because of the change in function signature? How about adding it as a validator property like `validator.root_instance`? Seems like it would make sense alongside `validator.schema`.

**Comment by Julian** [comment] 2019-12-14 21:13
> Would it be backwards incompatible because of the change in function signature?

Exactly yeah.

> How about adding it as a validator property like validator.root_instance

That couldn't work on `Validator`, since a single validator doesn't represent just one active validation, you can have one schema, and validate many instances with it, that's then entire point of `Validator` essentially, which is why some new thing would need to exist if it was to represent a single active validation.

**Comment by threewordphrase** [comment] 2019-12-14 21:20
If I alter `Validator.validate()` to add `validator.root_instance` like this:

```python
        def validate(self, *args, **kwargs):
            self.root_instance = args[0] # <==== added this line
            for error in self.iter_errors(*args, **kwargs):
                print('error?')
                raise error
```

and I print it out in my custom validator:

```python
schema = {
    "type" : "object",
    "properties" : {
        "price" : {
            "type" : "number",
            'equalsRef': {
                '$data': '1/name'
                }
            },
        "name_dupe" : {"type" : "string"},
        "name" : {
            "type" : "string",
            'equalsRef': {
                '$data': '1/name_dupe'
                }
            },
    },
}

instance = {
        'name': 'eggs',
        'name_dupe': 'not eggs',
        'price': 1234
        }

def equalsRefValidator(validator, value, instance, schema):
    print(validator.root_instance)
    print(instance)

custom_validators = {
        u'equalsRef': equalsRefValidator
        }

CustomValidator = extend(
            Draft7Validator,
            validators=custom_validators)

validator = CustomValidator(schema)

validator.validate(instance)
```

...it looks like it actually does exactly what I need:

```
~$python3 validate.py
{'name': 'eggs', 'name_dupe': 'not eggs', 'price': 1234}
{'name': 'eggs', 'name_dupe': 'not eggs', 'price': 1234}
{'name': 'eggs', 'name_dupe': 'not eggs', 'price': 1234}
1234
{'name': 'eggs', 'name_dupe': 'not eggs', 'price': 1234}
{'name': 'eggs', 'name_dupe': 'not eggs', 'price': 1234}
{'name': 'eggs', 'name_dupe': 'not eggs', 'price': 1234}
eggs
```

Am I missing something?

**Comment by Julian** [comment] 2019-12-14 21:25
Yes, it does what you need, but now breaks anytime anyone runs something like:

```
v = SomeValidator({"foo": "bar"})
first_errors = v.iter_errors("abcd")
second_errors = v.iter_errors("efgh")
do_something_with(first_errors, second_errors)
```

**Comment by Julian** [comment] 2019-12-14 21:29
Which -- if you're not doing that, and you don't mind it not working, you don't need what you changed either, just do what you usually do in this situation, use a closure.

I.e.

```python
def validate(instance, schema):
    root_instance = instance

    def equalsRefValidator(validator, value, instance, schema):
        print(root_instance)
        print(instance)

    extend(Draft7Validator, validators={u'equalsRef': equalsRefValidator})(schema).validate(
        root_instance,
    )


validate(...)
```

**Comment by threewordphrase** [comment] 2019-12-14 21:42
Thanks @Julian, I'll give that a shot. It would be great to have first class support for this use case though, I've had great success with AJV using its equivalent. AJV is one of the more popular js libraries and enabling interoperability between both libraries would benefit both communities greatly.

**Comment by Julian** [comment] 2019-12-14 21:47
Cool. Given the above what's the first class support that you'd be missing there? Seems reasonably easy to do what you want, no?

**Comment by Julian** [comment] 2019-12-14 21:48
(I'm inclined even to close the issue if what you were after is `$data` support -- looks fairly possible to me)

**Comment by threewordphrase** [comment] 2019-12-14 22:56
To be honest I'm not sure exactly what you mean when you say "you don't mind it not working" but it sounds like this approach might be a little hacky and not include some features of the library.

**Comment by Julian** [comment] 2019-12-14 23:05
The "you don't mind it not working" was meant to be about the way you did it previously (by actually modifying the source code -- that way breaks current library functionality) -- if you use a closure though, all the features of the library still work.

If anything the only hacky thing remaining there in the example code I gave is constructing a new validator class each time you validate, but you can get around that too with a bit more work.

So yeah I think personally this seems reasonable enough to do at this point to me, and everything should still work. Some day if anything like `$data` becomes part of the specification it will become part of this library too, but until then yeah I think this ticket at least is confirmed for me.

Happy to follow up if you still have questions or difficulties.

**Closed by Julian** 2019-12-14 23:05 UTC
Labels: Enhancement

**Comment by handrews** [comment] 2019-12-15 00:26
@threewordphrase It's easy for a single implementation to pick something and implement it as an extension, disregarding the concerns of others in the user community.

It's much harder to work out a solution that balances the concerns of all of the specification stakeholders and use cases.  No one has yet volunteered to take on that project with the specification.  The current spec authors, myself included, would prefer to see keywords targeted at specific use cases created as extension vocabularies, a concept added in the latest draft.  This avoids various concerns around `$data` violating the [rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power).

If someone volunteers to work through the concerns, it could get added in the future, but no one has even been willing to try that over the past four years that I've been involved with the spec.

**Comment by threewordphrase** [comment] 2019-12-15 20:38
@handrews I wasn't saying $data support should be added, just advocating that the root object should be passed down by default because it would make it easier for folks to build their own shims for libraries in different languages, DIY $data handling being one example.

**Comment by Julian** [comment] 2019-12-15 20:45
It's hard to predict these things, `$data` wants the root instance, some other behavior someone dreams up will want some other thing passed through. It's not like the root instance is the last remaining piece of state someone might want passed through, there are other examples.

I hear you about wanting to make your case simpler, but I have to consider the entirety of the library, and all of the use cases -- something being a part of the spec *forces* (or potentially forces) additional maintenance burden. But something not part of the spec, and still easy to do as an end user, as it seems $data is, there's only small benefit but potential big maintenance burden to accomodate.

**Comment by handrews** [comment] 2019-12-15 21:11
> It's hard to predict these things

This is actually part of why draft 2019-09 goes into detail on the classes of keywords (assertions, annotations, applicators, identifiers, and placeholders).  It provides sort of a bounding scope on what an implementation might need to do.

Note that the `links` keyword in Hyper-Schema does rely on instance data (it's a complex annotation, as opposed to most annotations that work with a single literal value).

Ideally, draft 2019-09 provides enough guidance to implement an extensible generic JSON Schema processor (which this particular library need not be- I'm not advocating that you implement Hyper-Schema, @Julian !).  At least assuming keyword designers follow the spec's recommendation to stay within that set of keyword classifiers.

The fact that there were no constraints on extension keyword behavior at all was really a problem for supporting extensibility.  You need *some* boundaries that you can reasonably assume.

**Comment by threewordphrase** [comment] 2019-12-17 03:20
Thanks for all your hard work on this project, guys... I know it must take a lot to beat back all the speculative feature requests from guys like me :)
