### ISSUE TITLE
Expose IValidator via PEP544 Protocols

### ISSUE THREAD

**Issue by corentinghigny** [Julian/jsonschema#548] opened 2019-04-02 14:40 UTC
I have an issue similar to #239 but somewhat different.
I would like to be able to reach IValidator to use type-hinting in functions.

If I want to create a function where a validator can be passed in parameter, it cannot be type-hinted:
```
def handle_ndjson(
  path:str, 
  validator:jsonschema.IValidator, 
  valid_object_fn: Callable[[dict], None], 
  invalid_object_fn: Callable[[dict, jsonschema.ValidationException], None]):
```
fails because `jsonschema.IValidator` isn't exposed (as explained in #239). 
The purpose is not to allow the creation of new validator, but to allow the user to chose between the different draft. Is there a graceful way to do that?

**Comment by Julian** [comment] 2019-04-02 15:06
Makes sense -- does whatever tool you're using properly support `zope.interface`? If so, happy to see that work resurrected.

**Comment by corentinghigny** [comment] 2019-04-02 16:14
I didn't know `zope.interface` so I played around a little and found some issues with it :
+ **isinstance**_(Class(), IClass)_ doesn't work. This is generally the way to check if type-hinting is abided by. 
+  In the IClass, "self" is not declared, but is in the Class. This might conflict when doing signature inspection. 
+ IDE _(IntelliJ)_ Integration for `zope.interface` is problematic. This is minor since IDE is a development tool but it's always nice to have a good environment. Currently, function in IClass with no parameter will appear as an error: `def hello(): """print a greating"""` will prompt you with `Method must have a first parameter`, and when type-hinting object (`class_instance: IClass = Class()`), parameter completion doesn't ask for the first parameter (since it expect "self"), which can add confusion

Generally, we can find class definition with `NotImplementedError` as the core of each function, but as you said in #239, "inheritance is not an appropriate tool to use for creating public APIs." (I am not sure why because I am not too well versed in public API so I'll take your word for it), but I feel like those kind of object are the best way handle type-hinting. It would be great to find a middle-ground

**Comment by Julian** [comment] 2019-04-08 01:13
Right so this is part of the reason type hinting really isn't very good :)

But rather than me pontificate, basically, what's the exact benefit you're hoping for here? Like, if type hinting can't express "this function takes an object implementing this interface" rather than "an object with this superclass" then yeah basically we're out of luck, I'm not willing to support the latter -- I'm happy to see a PR exposing an interface (using zope.interface, or some day someone will invent an even better version of an interfaces library for Python) but yeah beyond that, I don't have any great ideas myself here (and I haven't really used type hinting ever, so not very familiar with the tooling or ecosystem there). Ideas of course welcome, but yeah not ones that rely on exposing a concrete superclass, that much won't happen.

**Comment by Julian** [comment] 2019-04-23 12:44
Going to close this for cleanliness, but happy to continue the discussion if anyone has ideas on a decent path forward that doesn't involve inheritance.

**Comment by kojiromike** [comment] 2019-05-10 17:55
Would it be reasonable to try to implement a user defined protocol for a validator? https://mypy.readthedocs.io/en/latest/protocols.html#simple-user-defined-protocols

How do you feel about structural subtyping as described in PEP 544?

**Comment by Julian** [comment] 2019-05-11 22:43
@kojiromike that seems at least promising!

It seems to unfortunately have made all the mistakes ABCs made :( but it's at least reasonable enough of a design that I'd consider that. Need to read up on it, but yeah thanks a lot for the link!

**Comment by macdjord** [comment] 2021-03-23 02:02
Is there any movement on this? It's been almost 2 years now, and we still have no good way of demarking a generic validator class.

If the 'protocol' system isn't workable, can we just bite the bullet and use an abstract base class? For all their warts and faults, this *is * something they're entirely capable of: defining a shared interface which multiple concrete classes then implement.

This would also solve the issue that, due to the odd way the built-in validator classes are created by the `create()` factory function, some IDEs, such as PyCharm, fail to even recognise them as being instantiable classes, let alone correctly infer their API.

**Comment by Julian** [comment] 2021-03-23 02:07
Are you offering to send a PR?

**Comment by macdjord** [comment] 2021-03-23 02:48
I could do a PR for the ABC variant, if required.

**Comment by sirosen** [comment] 2021-12-09 20:56
I would be more than happy to contribute a PR to add a protocol for IValidator.

I basically plan to take the class from `docs/validate.rst` and turn it into a Protocol. I'll also see if we can get sphinx autodoc to pull the info from the protocol class.

I just have two quick questions before I start:

- Where does this belong? `validators.py`?
- How do we want to handle `typing_extensions`? Should it be added to `install_requires` for all versions or should I add `typing_extenions;python_version<"3.8"` (and handle the conditional import of Protocol)?

**Comment by Julian** [comment] 2021-12-09 21:07
That would be very much appreciated! Answers inline:

> Where does this belong? validators.py?

There's probably OK yeah, though I think I slightly prefer maybe calling it/putting it at `jsonschema.protocols.Validator`.

> should I add typing_extenions;python_version<"3.8"

I think this yeah, only add it conditionally on versions without it.

And yeah very much appreciate if you give this a shot!

**Comment by kojiromike** [comment] 2021-12-09 22:50
Would it make sense to introduce this protocol in https://github.com/python/typeshed/tree/master/stubs/jsonschema/jsonschema first?

**Comment by sirosen** [comment] 2021-12-09 23:27
I wasn't aware that `jsonschema` was in typeshed -- that's probably part of the right way to handle this.

I've never written a Protocol in a package which doesn't publish type information ([PEP 561](https://www.python.org/dev/peps/pep-0561/)). Adding a Protocol without a `py.typed` file present produces some odd semantics -- I'm pretty sure `mypy` will treat it as `Any`.

With `jsonschema` already in typeshed, it would be nice to annotate the type of `jsonschema.protocols.IValidator` there.
However, there is no concrete `jsonschema.protocols.IValidator` type. I think we need to create the protocol here, and then duplicate it in typeshed. `from jsonschema.protocols import IValidator` needs to work at runtime and type-checking time.

For right now, I'm going to try to get my branch to a point where it fully defines the protocol and drives autodoc (right now, doc builds are failing for me with nitpick errors because I've removed `jsonschema.IValidator`).

**Comment by sirosen** [comment] 2021-12-16 19:49
With this now in 4.3.0 (huge thanks @Julian for the steady review feedback and quick release!), I think we can close this issue.

I have [a PR open in typeshed](https://github.com/python/typeshed/pull/6614) to add this, after which it should be possible to use `jsonschema.Validator` for type annotations.

For those who did not see the PR, I'll also note here that `jsonschema.Validator` is `runtime_checkable`, meaning you can use it for `isinstance` checks.

**Closed** 2021-12-16 19:50 UTC
Labels: Enhancement, Help Wanted

**Comment by sirosen** [comment] 2022-02-22 19:20
That's how the typing information for all of typeshed works. `types-redis`, `types-requests`, etc. are all published from there.
I think it would have been simpler for libraries to either publish types or not, but there are enough smart people working on typeshed that I trust they have good reasons for it to exist.

The only thing that I can even imagine `jsonschema` doing about this is having doc somewhere that notes that there are type annotations available via typeshed as `types-jsonschema`.

Your PyCharm behavior indicates that you had an `__init__.pyi` file being picked up. I'm _guessing_ that you have a setup with PyCharm which is using an older version of typeshed. I don't know how PyCharm uses typeshed exactly, but that might be a direction to investigate.

**Comment by kojiromike** [comment] 2022-02-22 19:26
> The only thing that I can even imagine jsonschema doing about this…

(I suppose if jsonschema wanted to bring its types in-house it could get typeshed to close out that implementation without much fuss.)

**Comment by sirosen** [comment] 2022-02-22 19:53
Yes, having `jsonschema` publish types would also be a solution. Arguably the best solution for library consumers. But, not to downplay the value it offers, I don't think it's likely to happen in the near term.

`jsonschema` dynamically generates classes, and type checkers struggle to support dynamic cases like this. I see problems with trying to have `jsonschema` publish types based on its runtime logic. And I would argue that stubs will end up better maintained in typeshed than here.

**Comment by reitzig** [comment] 2022-02-24 10:20
> The only thing that I can even imagine jsonschema doing about this is having doc somewhere that notes that there are type annotations available via typeshed as types-jsonschema.

That would be good, yes.

FWIW, I was confused to see that the declaration of `class Validator` is local to a method. If it were moved (or a protocol) out of that method, an external protocol shouldn't be necessary.

> Your PyCharm behavior indicates that you had an __init__.pyi file being picked up. I'm guessing that you have a setup with PyCharm which is using an older version of typeshed. I don't know how PyCharm uses typeshed exactly, but that might be a direction to investigate.

The part above the line was without the typeshed dependency; sorry for that. With that dependency, PyCharm handles things as you would expect. Well, "go to definition" is useless, obviously, but that's by design of externalized protocols.

**Comment by kojiromike** [comment] 2022-02-24 13:58
> I was confused to see that the declaration of class Validator is local to a method.

I also found this to be a challenge in typing.

**Comment by sirosen** [comment] 2022-02-24 14:44
I think this is moving towards a new topic, which is "how can the `jsonschema` runtime code be altered to support typing". I think a new issue, rather than continuing here, might be appropriate.

I'm not sure why the code is structured the way it is. Inheritance is being intentionally avoided, and inheritance is the most obvious way to share code between classes in this case. I think the right etiquette is therefore to assume that there's a good reason for that, and to try to understand that before proposing any concrete changes.

**Comment by Julian** [comment] 2022-02-24 14:48
(Thanks @sirosen, indeed a good response, so will use it to comment)

> I think this is moving towards a new topic, which is "how can the jsonschema runtime code be altered to support typing".

Just to head this off, I am not very interested in this topic. Certainly not without any proposed concrete benefit. Feel free to open an issue if you'd like to make a case, but be prepared to list good reasons.

>  I think the right etiquette is therefore to assume that there's a good reason for that

Yes please. In particular, there are closures happening there. But also indeed a desire not to have any inheritance [nor encourage it in any public APIs](https://en.wikipedia.org/wiki/Composition_over_inheritance).
