### ISSUE TITLE
Make $schema lookup more liberal for empty fragment URLs

### ISSUE THREAD

**Issue by jswinarton** [Julian/jsonschema#569] opened 2019-06-12 15:04 UTC
I have a valid schema document that contains the following `$schema` value:

```
{
  "$schema": "http://json-schema.org/draft-07/schema/#"
}
```

When validating an instance against this schema, I get the following warning: 

```
/usr/local/lib/python3.7/site-packages/jsonschema/validators.py:893: DeprecationWarning: The metaschema specified by $schema was not found. Using the latest draft to validate, but this will raise an error in the future.
```

I discovered that I can suppress the error by changing removing the trailing slash and hash from the schema URI, e.g. `http://json-schema.org/draft-07/schema`. 

I think the validator should allow for some variations on URI formats--the JSON Schema documentation specifies the `$schema` value _with_ the trailing slash and hash, so I believe that will be the most common format users attempt.

**Comment by Julian** [comment] 2019-06-14 18:33
This looks reasonable -- I'm not sure we want to accept multiple variations on its own, but really it depends what the JSON Schema spec says (if anything) about whether those URLs are the same or not as far as its concerned. Probably you're right that they are.

So yeah definitely thanks for filing.

**Comment by scottj97** [comment] 2019-07-03 00:47
I second this request. The "official" guide [recommends `http://json-schema.org/schema#`](https://json-schema.org/understanding-json-schema/reference/schema.html) but that gives this warning from jsonschema. In this case, removing the trailing hash mark does not help. It looks like I must specify an explicit version (and also remove the trailing slash+hash).

**Comment by Julian** [comment] 2019-07-03 01:04
That... I think is actually a bad recommendation by our tutorial.

JSON Schema does not make any forwards compatibility guarantees, and has broken some significant compatibility in recent versions, so I can't think of any good reason a schema author should declare that URL.

We should discuss upstream in the tutorial repo, but yeah that one is way less reasonable sounding to me than the original request here.

**Comment by jayeye** [comment] 2019-08-14 21:35
Since a json schema is itself a json document that should match the "metaschema" in `http://json-schema.org/schema`, I should be able to use the validator to make sure my schema is correct (at least syntactically). I can validate json data against a schema I wrote, but I cannot validate my schema against the metaschema. 

Also: maybe my understanding of JSON Schema is lacking, but shouldn't validating the metaschema against itself work?
`curl -s http://json-schema.org/schema > ms`
then in python: `jsonschema.validate(instance=json.load(open('ms')), schema=json.load(open('ms')))`

I get an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 540, in validate
    cls.check_schema(schema)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 83, in check_schema
    raise SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: True is not of type 'object'
```

The source of the problem is that the metaschema has a bunch of naked `true` and `false` (so, booleans, not strings), which apparently confuse the validator. Or maybe *I* am confused? (more likely :) )

**Comment by wmarcuse** [comment] 2020-07-30 20:59
I get the same `DepriciationWarning` when I create a reusable schema validator:
```
validator_class = jsonschema.validators.validator_for(SCHEMA)
validator = validator_class(schema=SCHEMA, format_checker=jsonschema.FormatChecker())
```

Specifying the draft version validator did the trick:

```
validator_class = jsonschema.validators.Draft7Validator
validator = validator_class(schema=SCHEMA, format_checker=jsonschema.FormatChecker())
```

**Comment by lcvisser** [comment] 2021-04-01 15:34
Maybe also accept both `http://` and `https://`?

**Comment by anriijmind** [comment] 2021-04-17 17:40
@wmarcuse Could you give, please, an example with validating schema and response? Because I don't understand what should I do with `validator = validator_class(schema=SCHEMA, format_checker=jsonschema.FormatChecker())`, if warning shows in that code
`validate(instance=respose_json, schema=schema)`
Schema has this type `"$schema": "http://json-schema.org/schema#"`

and I have this error:
`/lib/python3.8/site-packages/jsonschema/validators.py:928: DeprecationWarning: The metaschema specified by $schema was not found. Using the latest draft to validate, but this will raise an error in the future.
    cls = validator_for(schema)`

**Comment by Hoohm** [comment] 2021-06-07 14:01
I have the same error as you @anriijmind 
Using this link : `http://json-schema.org/draft/2020-12/schema`

**Comment by anriijmind** [comment] 2021-06-07 15:04
> I have the same error as you @anriijmind
> Using this link : `http://json-schema.org/draft/2020-12/schema`

Still warning shows.
Tried:
1. `"$schema": "http://json-schema.org/schema#"` -> `"$schema": "http://json-schema.org/draft/2020-12/schema#"`
2. `"$schema": "http://json-schema.org/schema#"` -> `"$schema": "http://json-schema.org/draft/2020-12/schema"`

I have `jsonschema "version": "==3.2.0"`

**Comment by Kaelink** [comment] 2021-07-02 20:18
I had the same issue, but the README only claims support for:
> Full support for Draft 7, Draft 6, Draft 4 and Draft 3

Changing to `http://json-schema.org/draft-07/schema#` therefore solved the warning in my case.

**Comment by anriijmind** [comment] 2021-07-05 07:58
> I had the same issue, but the README only claims support for:
> 
> > Full support for Draft 7, Draft 6, Draft 4 and Draft 3
> 
> Changing to `http://json-schema.org/draft-07/schema#` therefore solved the warning in my case.

Thanks, it solves warning

**Comment by lcvisser** [comment] 2021-07-10 21:53
@Julian PR #822 resolves this elegantly (in my opinion at least).

**Comment by Julian** [comment] 2021-09-30 11:54
Given the combination of some of what's proposed here being against the spec, and the rest being fairly easy to do by either ensuring you use precisely the identifier that the meta schema says you should, I'm going to WONTFIX this.

You can see some additional discussion at the bottom of #822.

If you really insist on (or have a use case where) you cannot change what's in the actual schema itself, something like `your_schema["$schema"] = Draft4Validator.META_SCHEMA["$id"]` works as well.

**Closed by Julian** 2021-09-30 11:54 UTC
Labels: Bug
