### ISSUE TITLE
Non-unique array items with uniqueItems=True does not fail validation in 4.0.1+

### ISSUE THREAD

**Issue by DrGFreeman** [Julian/jsonschema#872] opened 2021-11-03 00:27 UTC
## Description

An array with non-unique items does not fail validation when `uniqueItems` is True.

## Steps to reproduce

Run the following test:

```python
import jsonschema
import pytest


def test_unique_items():
    """names has non-unique items and is expected to raise a validation error."""
    instance = {"names": ["foo", "bar", "foo"]}
    schema = {
        "properties": {"names": {"type": "array", "uniqueItems": True}},
        "type": "object",
    }

    with pytest.raises(
        jsonschema.exceptions.ValidationError, match="Failed validating 'uniqueItems'"
    ):
        jsonschema.validate(instance=instance, schema=schema)
```

## Expected behavior

The test is expected to pass, i.e. a `jsonschema.exceptions.ValidationError` is raised:

```
jsonschema.exceptions.ValidationError: ['foo', 'bar', 'foo'] has non-unique elements

    Failed validating 'uniqueItems' in schema['properties']['names']:
        {'type': 'array', 'uniqueItems': True}

    On instance['names']:
        ['foo', 'bar', 'foo']
```

## Actual behavior

The test fails, i.e. no exception is raised:

```python
>           jsonschema.validate(instance=instance, schema=schema)
E           Failed: DID NOT RAISE <class 'jsonschema.exceptions.ValidationError'>
```

Version affected: 4.0.1 and up;

```
nox > Ran multiple sessions:
nox > * tests(jsonschema='3.2.0'): success
nox > * tests(jsonschema='4.0.1'): failed
nox > * tests(jsonschema='4.1.0'): failed
nox > * tests(jsonschema='4.1.1'): failed
nox > * tests(jsonschema='4.1.2'): failed
```

**Comment by Julian** [comment] 2021-11-03 00:31
Hi. Can you include an example that runs the same thing on both versions? Your schema doesn't set a `$schema` key to declare what version you're trying to use, so you're comparing behavior across two different versions of the JSON Schema specification.

**Comment by Julian** [comment] 2021-11-03 00:33
OK I see, setting that myself, this looks like a duplicate of the unfortunate #866.

A PR is definitely welcome, tests are needed upstream as a first step.

**Closed by Julian** 2021-11-03 00:33 UTC

**Comment by DrGFreeman** [comment] 2021-11-03 00:38
Oh! Sorry for the duplicate, I had looked for this issue but that was a few weeks ago and did not verify again before raising this one.
