### ISSUE TITLE
Validation error, fails to disambiguate oneOf on enum

### ISSUE THREAD

**Issue by solenskiner** [Julian/jsonschema#361] opened 2017-09-18 12:29 UTC
`jsonschema.exceptions.ValidationError: {'channel': 'diff_order_book', 'event': 'data', 'currency_pair': 'btcusd', 'data': {'timestamp': '1505736811', 'bids': [], 'asks': [['3959.97000000', '2.51820000'], ['3966.97000000', '0.13028842'], ['3969.75000000', '5.04080000'], ['3969.78000000', '0'], ['4089.46000000', '4.39971275']]}} is valid under each of {'properties': {'channel': {'type': 'string', 'enum': ['order_book']}}, 'required': ['channel'], '$ref': 'bitstamp/order_book.json'}, {'properties': {'channel': {'type': 'string', 'enum': ['diff_order_book']}}, 'required': ['channel'], '$ref': 'bitstamp/diff_order_book.json'}`

```
Failed validating 'oneOf' in schema:
    {'$schema': 'http://json-schema.org/draft-06/schema#',
     'name': 'bitstamp',
     'oneOf': [{'$ref': 'bitstamp/diff_order_book.json',
                'properties': {'channel': {'enum': ['diff_order_book'],
                                           'type': 'string'}},
                'required': ['channel']},
               {'$ref': 'bitstamp/live_orders.json',
                'properties': {'channel': {'enum': ['live_orders'],
                                           'type': 'string'}},
                'required': ['channel']},
               {'$ref': 'bitstamp/live_trades.json',
                'properties': {'channel': {'enum': ['live_trades'],
                                           'type': 'string'}},
                'required': ['channel']},
               {'$ref': 'bitstamp/order_book.json',
                'properties': {'channel': {'enum': ['order_book'],
                                           'type': 'string'}},
                'required': ['channel']}],
     'properties': {'currency_pair': {'enum': ['btcusd',
                                               'btceur',
                                               'eurusd',
                                               'xrpusd',
                                               'xrpeur',
                                               'xrpbtc',
                                               'ltcusd',
                                               'ltceur',
                                               'ltcbtc',
                                               'ethusd',
                                               'etheur',
                                               'ethbtc'],
                                      'type': 'string'}},
     'required': ['currency_pair'],
     'type': 'object'}

On instance:
    {'channel': 'diff_order_book',
     'currency_pair': 'btcusd',
     'data': {'asks': [['3959.97000000', '2.51820000'],
                       ['3966.97000000', '0.13028842'],
                       ['3969.75000000', '5.04080000'],
                       ['3969.78000000', '0'],
                       ['4089.46000000', '4.39971275']],
              'bids': [],
              'timestamp': '1505736811'},
     'event': 'data'}
```

**Comment by Julian** [comment] 2017-09-18 12:37
Hi, can you be a bit more specific please, pasting a long error traceback into a box is not a bug report :).

Just at a glance though, your schema does say draft 6, but draft 6 support is not yet released, it's just on a branch, so unless you've installed that branch, you're unlikely to work there.

**Comment by solenskiner** [comment] 2017-09-18 13:14
the enum on channel uniquely disambiguates the oneOf, as apparent from the jsonschema-barf, yet fails to disambiguate the it

**Comment by Julian** [comment] 2017-09-18 13:46
Sorry, I still don't know what you mean, please elaborate rather than me guessing -- I think you probably are talking about having different branches in your oneOf that you expect to recurse into, but that's not how `oneOf`('s error message) works, it will never guess at a specific error unless you use something like `jsonschema.exceptions.best_match`, which will.

**Comment by solenskiner** [comment] 2017-09-18 13:50
there is no error. both arms match. the channel is what disambiguates between them. or rather, should.

**Comment by Julian** [comment] 2017-09-18 14:24
Please include:

* Your full schema
* Your full instance
* Whatever code you're using to validate one with the other
* A description of the behavior you expect to see, e.g. "I expect this output: `foo`"
* A description of the behavior you actually see, with an explanation for how it differs from what you expected

It seems possible that another thing you might not be aware of is that `$ref`, by the spec, causes all other validators to be ignored, but you have other things in there alongside it (which will be ignored). But I really really do not want to be guessing what you mean, please do include full information about what you're referring to.

**Comment by Julian** [comment] 2017-10-01 01:28
I think one of the above 2 issues is likely to be yours, so going to close this, but feel free to respond back with more detail if you're still having any issues.

**Closed by Julian** 2017-10-01 01:28 UTC
