### ISSUE TITLE
Package cannot be deployed as dependency using bdist_msi

### ISSUE THREAD

**Issue by duk3luk3** [Julian/jsonschema#389] opened 2018-02-04 07:28 UTC
Hello,

the package requires the `jsonschema/schemas/draft3.json` file to work.

This file isn't included when creating an msi installer using bdist_msi. (See here: https://github.com/FAForever/client/issues/984 )

I think you might need to add `jsonschema/schemas *` to your MANIFEST.in.

**Comment by Wesmania** [comment] 2018-02-04 11:05
To add more context, we're using cx_Freeze to package Python modules for our program. It seems this is a duplicate of https://github.com/Julian/jsonschema/pull/162, so adding zip_includes may work for us, though I don't know if it's just a workaround for an actual issue.

**Comment by Julian** [comment] 2018-02-06 22:04
Hey! Thanks.

I think we're currently using the best existing way to open files without assuming they're on a filesystem (pkgutil), so I would assume the fix should probably be external, yeah, but happy to review a PR to change that if it turns out not to be the case, long as yeah it comes with a test ensuring that if cx_Freezing works now, it continues to work.

Closing for now but lemme know if it turns out there's what to do here.

**Closed by Julian** 2018-02-06 22:04 UTC
