### ISSUE TITLE
jsonschema doesn't validate date format in draft v4

### ISSUE THREAD

**Issue by jakul** [Julian/jsonschema#385] opened 2018-01-16 17:33 UTC
I've noticed that `jsonschema` doesn't validate date format in draft v4. 

It looks like the cause is https://github.com/Julian/jsonschema/blob/aaee55c9f6eea1abd37ca7a2537d586f8940971c/jsonschema/_format.py#L233, which only adds the format checker to V3.

**Comment by handrews** [comment] 2018-01-16 18:44
Technically, "date" was not part of draft-04 (although many implementations offer it, "time", and "regex" as extensions, and I have no idea why they were removed after draft-03- we put them back in draft-07).

**Comment by Julian** [comment] 2018-01-16 22:25
Yeah, I don't know that I have a strong opinion one way or the other on supporting this anyhow even though it isn't in the spec, but it would need tests (and there aren't tests for it upstream in the test suite because my opinion there was not to *force* implementations to add a thing that isn't in the spec).

So if this was merged, yeah, it'd need tests within this repo specifically :)

On the other hand, this is pretty easy to do (by design) as an end user via `FormatChecker.checks` + the draft 3 format checker, so I might recommend you have a look at that too if you haven't already.

**Comment by jakul** [comment] 2018-01-17 10:34
I'm not following/reading the drafts, but just from the source code here it confused me that `date-time` is in Draft 3 and 4, but `date` is only in Draft 3.

I'd actually err on the side of making this implementation follow the spec closely, and use documentation to highlight where end-users may want to add extra checks themselves.

I looked to add some tests, but am not sure what I would actually be testing. Would it just be to check that there is a format checker called `date` in `draft4_format_checker.checkers`?

**Comment by Julian** [comment] 2018-01-17 12:47
> I'd actually err on the side of making this implementation follow the spec closely, and use documentation to highlight where end-users may want to add extra checks themselves.

This would be fine with me certainly -- I believe there's already some docs on adding format checkers, but if you see any gaps there certainly happy to accept patches for it.

**Comment by Julian** [comment] 2018-01-25 09:35
Gonna close this specific issue for now then, and happy to review any PRs to improve the docs?

Lemme know if you have anything further.

**Closed by Julian** 2018-01-25 09:35 UTC
