### ISSUE TITLE
RefResolver breaks on file:// URIs

### ISSUE THREAD

**Issue by afaulconbridge** [Julian/jsonschema#478] opened 2018-10-22 15:48 UTC
When using a `file://` in a RefResolver to resolve relative URI references it fails with:
```
jsonschema.exceptions.RefResolutionError: addinfourl instance has no attribute '__exit__'
```

This is because `urllib.urlopen()` can't be used in a `with` clause - see https://stackoverflow.com/questions/30627937/traceback-attributeerroraddinfourl-instance-has-no-attribute-exit for details.

I can create a minimal example if needed, and I'll submit a pull request for the fix.

**Comment by Julian** [comment] 2018-10-22 15:53
Hi, when filing issues please always include what version you're on (and a minimal reproducer yeah), but this sounds like #472, which is fixed on master, though looks like not in an alpha release yet -- what version are you on?

**Comment by Julian** [comment] 2018-10-25 17:50
I think the above is the case, but if not lemme know and happy to have another look!

**Closed by Julian** 2018-10-25 17:50 UTC
