### ISSUE TITLE
Use of importlib_metadata breaks jsonschema usage in AWS Lambda

### ISSUE THREAD

**Issue by BAllbeeEplexity** [Julian/jsonschema#628] opened 2019-11-19 21:19 UTC
While trying to use this library (through [`python-jsonschema-objects`](https://pypi.org/project/python-jsonschema-objects/), to generate classes) for a project running in an AWS Lambda, the attempt to retrieve the package `__version__` using

```python
__version__ = metadata.version("jsonschema")
```
raises a `PackageNotFoundError` — `importlib_metadata` cannot be found, despite it being installed.

I have worked around this by simply replacing that dunder-value with the actual version-value retrieved (`'3.2.0'` in this case), but thought it might be worth bringing to your attention, particularly since the `__version__` should be a constant for any given release, and there's no obvious benefit to calculating it vs. using any of [several other options](https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package) that aren't beholden to yet another library. ;-)

**Comment by Julian** [comment] 2019-11-19 22:12
Hi. Sorry you're having trouble.

This is a duplicate of #584 (and relatedly #614).

For which my position is still essentially "these are unsupported environments at the minute due to lack of CI, and more specifically that this particular issue is a bug in Lambda".

Happy to hear further thoughts, ideally in #584, but yeah I don't see this changing unfortunately.

**Closed by Julian** 2019-11-19 22:12 UTC

**Comment by BAllbeeEplexity** [comment] 2019-11-19 22:24
Well, since I have a relatively simple workaround, I won't pursue too much further, then, but I'd disagree that it's the same issue, or even an unsupported environment, if only because all the requisite packages are present (see screencap). Yes, it takes building a deployment ZIP, but I can take that same zip, drop it on any machine that the individual libraries run on, and it works just fine.

The fact that changing that one line, hardcoding the version-number instead of using a library that may not work under Lambda, allows at least the basic functionality to work, would indicate that the problem's not in this library directly, but in using importlib_metadata to retrieve the package version from…wherever.

Thank you for the quick reply, at any rate. :-)

![Screenshot from 2019-11-19 15-19-38](https://user-images.githubusercontent.com/26661644/69191679-2f419280-0ae0-11ea-9e16-f4bc2c037584.png)

**Comment by Julian** [comment] 2019-11-19 22:34
importlib_metadata retrieves installed package metadata. Normal Python
deployments install packages.

If you don't install a package, you can't retrieve its metadata.

Lambda seems to have decided not to install packages from what users
report. That's not supported. Other packages besides jsonschema will break
(for other reasons with the same root cause. In your zip example, for
reasons like compiling a package with C extension for the wrong platform).

And yeah just any environment that doesn't run in CI is not supported.
You'll note your issue is specific to Lambda, so it's certainly different
:). Surely you can understand not supporting environments that cannot be
guaranteed to continue to function because they're not being tested.

**Comment by BAllbeeEplexity** [comment] 2019-11-20 00:05
> Surely you can understand not supporting environments that cannot be guaranteed to continue to function because they're not being tested.

Sure. Don't get me wrong, I don't disagree, philosophically, with that decision — I don't have enough insight into the behind-the-scenes efforts and processes to have more than a vague and perhaps unfounded opinion, and one that's driven by immediate need at that. :-)

Since I've got a workaround — basically just copying the source-of-truth version from the `METADATA` file into the code in place of the only call to the real problem package that I can find anywhere in `jsonschema` — which takes care of it, I'm not too concerned, at least for now. I'm intrigued (and slightly amused) that the decision for the where that source-of-truth version is the *only* thing preventing this package from being usable in Lambda, though. :-D

Again, thanks!

**Comment by Julian** [comment] 2019-11-20 00:29
Cool! Glad your workaround is working, happy to hear that certainly!

Hopefully anyone else running into this finds it, so definitely appreciate filing the issue.

**Comment by BAllbeeEplexity** [comment] 2019-11-20 00:40
So far, at least. :-) No worries!

I may write it up in more detail, and could share it here if there'd be any interest.

**Comment by freekwiekmeijer** [comment] 2019-12-11 09:31
In case the AWS Lambda is deployed using Serverless framework, there is a very simple workaround: http://biercoff.com/how-to-fix-package-not-found-error-importlib-metadata/

**Comment by AlexThomas90210** [comment] 2019-12-13 18:42
@BAllbeeEplexity Can you share your fix? I have having the same issue in a lambda function.

@freekwiekmeijer solution is not working for me, maybe because I am putting jsonschema inside a lambda layer

**Comment by BAllbeeEplexity** [comment] 2019-12-13 20:29
I have two that I can share. :-)

The first is quicker and easier, but is _not_ a stable fix — It'd have to be re-applied any time there was an update to this package. It basically boils down to commenting out the last line in `jsonschema.__init__.py` like so:

`# __version__ = metadata.version("jsonschema")`

The better solution in my case may or may not work for you, but might be adaptable. I'm (for now manually) building a Lambda deployment-package (a ZIP file) after each dev-test cycle, and manually deploying it in the AWS Lambda console. I've attached a stripped-down copy of the (kludgy? Brute-force?) script I'm using to do that, which basically:
*   Reads the requirements.txt file, 
*   Finds the code- and metadata-directories and files in the `pipenv` environment for the project for each package in requirements.txt (dealing with known packages where those directory-names don't match the package-name — e.g., 
    *   attrs => attr, 
    *   python-jsonschema-objects => python_jsonschema_objects)
*   Adds them to the zip-archive

Attaching a screen-cap of the relevant example (with customer-sensitive information blacked out, sorry, ;-) ). The various "`S.json`" items in that screen-cap are JSON schema definitions that the code uses. 

Ultimately, as far as I can tell, as long as you get the code- and metadata-directories _both_ in the Lambda package, it will work. I presume, though I haven't tested it, that a variation of the same process would work in a Lambda Layer.

Attachments:
[generic-lambda-package-builder.txt](https://github.com/Julian/jsonschema/files/3962465/generic-lambda-package-builder.txt) (GitHub won't allow attachment of Python files to comments? Wow. O.o )
[example-deployment-package](https://user-images.githubusercontent.com/26661644/70829513-33916080-1dab-11ea-835e-612a05adead8.png)

**Comment by sergeyv** [comment] 2021-08-02 21:36
FWIW, I was getting the same issue on a "plain" Linux VM running UWSGI/zc.buildout stack - not sure which one makes the environment "incompatible" with jsonschema but it works just fine for every other third-party dependency I have. So perhaps the approach used by jsonschema is a bit fragile?

Wasted a couple of hours tinkering, switched to a different library.
