### ISSUE TITLE
Bundling schema resources into a single document 

### ISSUE THREAD

**Issue by letmaik** [Julian/jsonschema#891] opened 2021-12-10 09:22 UTC
[JSON Schema bundling](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.appendix.B.1) is often required for packaging scenarios. In particular, bundling without reference removal seems relatively straightforward. Is this something that could be in scope for this library?

**Comment by Julian** [comment] 2021-12-20 14:06
Hi. I think this is a duplicate of #692 (and that yes it'd be acceptable to PR!)

**Closed by Julian** 2021-12-20 14:06 UTC
