### ISSUE TITLE
Json schema 3.2.0 pip package no longer supports Python 2.7

### ISSUE THREAD

**Issue by magnus-rovco** [Julian/jsonschema#734] opened 2020-09-09 17:32 UTC
Json schema 3.2.0 pip package requires pyrsistent, when attempting to install it now gives the following error:
```
pyrsistent requires Python '>=3.5' but the running Python is 2.7.17
```
The latest release of pyrsistent (0.16.0) has dropped support for 2.7

**Comment by PatMyron** [comment] 2020-09-09 18:15
looks like a duplicate of https://github.com/Julian/jsonschema/issues/732 and https://github.com/Julian/jsonschema/issues/733

**Comment by Julian** [comment] 2020-09-09 18:21
Yep.

**Closed by Julian** 2020-09-09 18:21 UTC
