### ISSUE TITLE
2.5.1 doesn't depend on functools32 under python2.7

### ISSUE THREAD

**Issue by grimmy** [Julian/jsonschema#234] opened 2015-06-17 16:08 UTC
Installing 2.5.1 from scratch under python 2.7.3 works goes fine, but then explodes on a missing import (functools32) when trying to import.

````python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonschema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/exceptions.py", line 6, in <module>
    from jsonschema import _utils
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import str_types, MutableMapping, urlsplit
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/compat.py", line 39, in <module>
    from functools32 import lru_cache
ImportError: No module named functools32
````

But on python 2.7.9 everything is fine

````python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonschema
>>> 
````

My test environments are docker containers running debian wheezy and debian jessie.

**Comment by dnephin** [comment] 2015-06-17 16:09
Duplicate of #233

**Comment by Julian** [comment] 2015-06-17 16:14
Yeah, thanks!

I'm still undecided on whether it's appropriate to fix or just leave it at "you'll need a recent version of pip". There are ways to support older versions (`twine` does them), but it's additional effort.

**Closed by Julian** 2015-06-17 16:14 UTC
