### ISSUE TITLE
pyrsistent Requirement no 2.7 support

### ISSUE THREAD

**Issue by bishopbm1** [Julian/jsonschema#735] opened 2020-09-09 20:26 UTC
When trying to install we get an error on the requirements:

```
Collecting pyrsistent>=0.14.0 (from jsonschema->-r /opt/stackstorm/packs/encore/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7d/ae/90ddcf28fb8eee5d4990920586d2856342e42faa95f39223f0b9762ef264/pyrsistent-0.17.2.tar.gz
 (stderr: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ERROR: pyrsistent requires Python '>=3.5' but the running Python is 2.7.5
```

It looks like their latest version dropped support for python 2.7.

**Comment by Julian** [comment] 2020-09-09 20:40
Hi, this is a dupe of #732 (and #733 and #734 :) have a look there at the link to the upstream ticket where this fix should go.

Also, will mention quickly that from your error message -- `jsonschema` 3.2 *does* support 2.7, but only technically on versions of Python that didn't end of life :) (i.e. PyPy).

You've probably heard this message enough at this point, but if you are going to continue to run 2.7 (which may very well make sense in your situation), you definitely should be doing so on a version of 2.7 that isn't dead :).

**Closed by Julian** 2020-09-09 20:40 UTC
