### ISSUE TITLE
"RefResolutionError" exception raised when resolving "$ref"

### ISSUE THREAD

**Issue by warner121** [Julian/jsonschema#570] opened 2019-06-17 13:16 UTC
Taking the example from the json-schema documentation on structuring complex schema: [https://json-schema.org/understanding-json-schema/structuring.html](url).

I create a file **address_pass.json** where address is defined internally:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": { "$ref": "#/definitions/address" }
  }
}
```
The code below illustrates this validates the example instance:
```python
import json
from jsonschema import validate

instance = {
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}

with open('address_pass.json') as json_data:
    schema = json.load(json_data)
    json_data.close()
    
validate(instance=instance, schema=schema)
```
All good. Now, the example does not define the content of **definitions.json** but I believe it should look like this:
```
{
  "address": {
    "type": "object",
    "properties": {
      "street_address": { "type": "string" },
      "city":           { "type": "string" },
      "state":          { "type": "string" }
    },
    "required": ["street_address", "city", "state"]
  }
}
```
With corresponding reference from within **address_fail.json** as below:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "definitions.json#/address" },
    "shipping_address": { "$ref": "definitions.json#/address" }
  }
}
```
However, the same code as above now fails with the RefResolutionError reported above:
```python
import json
from jsonschema import validate

instance = {
  "shipping_address": {
    "street_address": "1600 Pennsylvania Avenue NW",
    "city": "Washington",
    "state": "DC"
  },
  "billing_address": {
    "street_address": "1st Street SE",
    "city": "Washington",
    "state": "DC"
  }
}

with open('address_fail.json') as json_data:
    schema = json.load(json_data)
    json_data.close()
    
validate(instance=instance, schema=schema)
```
Furthermore, replacing ```$ref``` with ```file``` and a full path to **definitions.json**  illustrates the external reference does work. So the issue seems to be simply in locating the file.

**Comment by Julian** [comment] 2019-06-19 13:52
Thanks for including the full reproducer, will have a look.

**Comment by demitri** [comment] 2019-07-02 00:26
Just wanted to +1 this and receive notifications; I ran into the same issue. Replacing `$ref` with `file` and specifying the full path worked for me as well, but it's not clear to me whether something like:

```
{ "$ref" : "file_in_same_dir#/definitions/thingy }
```

is supported at all? Relative references are valuable as the code moves from machine to machine.

**Comment by radeklat** [comment] 2019-07-17 12:51
The same as @demitri here.

**Comment by Julian** [comment] 2019-09-08 17:05
@demitri it is if you specified a base URI -- either in your schema or to the resolver (i.e. `RefResolver(base_uri=whateverDirectoryYouWantRelativeTo)` -- did you do that?

**Comment by Julian** [comment] 2019-09-08 17:06
@warner121 which looks like your issue too -- you didn't specify a base URI to a resolver and pass that to validate, so JSON Schema has no way to know what directory you mean to resolve relative to.

**Comment by Julian** [comment] 2019-09-08 23:51
Closing, because I think you're both looking for the above, but feel free to follow up with comments if you do think there's an issue here.

**Closed by Julian** 2019-09-08 23:51 UTC
Labels: Bug

**Comment by RomainTT** [comment] 2020-01-10 15:40
Hi,
I think this is actually an issue. In the [documentation](https://json-schema.org/understanding-json-schema/structuring.html?highlight=ref#structuring-a-complex-schema) of json-schema, it is stated:

>  $ref can also be a relative or absolute URI, so if you prefer to include your definitions in separate files, you can also do that. For example:
> 
> `{ "$ref": "definitions.json#/address" }`
> would load the address schema from another file residing alongside this one.

And:

> The $id property is a URI that serves two purposes:
> - It declares a unique identifier for the schema.
> - It declares a base URI against which $ref URIs are resolved.
> 
> […]
> 
> But be aware of the second purpose of the $id property: that it declares a base URL for relative $ref URLs elsewhere in the file. For example, if you had:
> 
> `{ "$ref": "person.json" }`
> in the same file, a JSON schema validation library that supported network fetching would fetch person.json from http://foo.bar/schemas/person.json, even if address.json was loaded from somewhere else, such as the local filesystem.

My understanding is that `id` **can** be given to provide a base url, but it can also be omitted and the implementation should search by default in the relative path of the schema.

You wrote *“jsonschema has no way to know what directory you mean to resolve relative to”*, but why not to take the given path of the schema ? (that you have, because you can read the file).

**Comment by Julian** [comment] 2020-01-10 15:54
> You wrote “jsonschema has no way to know what directory you mean to resolve relative to”, but why not to take the given path of the schema ? (that you have, because you can read the file).

In the examples in this ticket `jsonschema` *doesn't* read the file. It's simply invoked after the calling code did so itself.

**Comment by RomainTT** [comment] 2020-01-14 13:46
My bad ! Personally, I have the same issue but while using it from the command line. Is it supposed to work ?

**Comment by Julian** [comment] 2020-01-14 14:40
Ah -- so, in that case at the minute it doesn't (i.e. the CLI parser
doesn't save the path in a RefResolver), but in theory yep that could be
made to work.

Happy to see a PR doing so if you'd be interested!

**Comment by demitri** [comment] 2020-04-06 06:57
Hi @Julian,

Sorry, it took me a while to test this again. Unfortunately, I'm just not getting this to work. Hopefully I'm only missing something stupid. Here is my main schema:

**`gaia_dr2_record_response.json`**
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://trillianverse.org/schemas/datasets/gaia/gaia_dr2_record_response.json",
    "title": "Gaia DR2 Source Catalog Record Schema",
    "type": "object",
    "additionalProperties" : false,
    "properties" : {
        "$ref" : "gaia_dr2_properties.json#/definitions/GaiaDR2Properties/properties"
    }
}
```

A second schema file containing the properties, **`gaia_dr2_properties.json`**:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://trillianverse.org/schemas/datasets/gaia/gaia_dr2_properties.json",
    "type": "object",
    "definitions": {
        "GaiaDR2Properties" : {
            "properties": {
                "solution_id" : {
                    "type": "integer",
                    "enum" : [1635721458409799680]
                },
                "designation" : {
                    "type": "string",
                    "pattern": "^Gaia DR2 [0-9]{19}$"
                },
                "source_id" : {
                    "type": "integer",
                    "minimum" : 4295806720,
                    "maximum" : 6917528997577384320
                }
            }    
        }
    }
}

```

And my script **`test.py`**:
```python
#!/usr/bin/env python

import os
import json

from jsonschema import RefResolver, Draft7Validator

with open("gaia_dr2_properties.json") as schema_file:
    properties_schema = json.loads(schema_file.read())
	
with open("gaia_dr2_record_response.json") as schema_file:
    response_schema = json.loads(schema_file.read())

data_string = '''{
  "source_id": 4038848092638268032,
  "solution_id": 1635721458409799680,
  "designation": "Gaia DR2 1635721458409799680"
}'''
data = json.loads(data_string)

file_path = os.path.abspath(__file__)
base_uri = f"file:{file_path}"
print(f"\nbase uri = '{base_uri}'\n")
resolver = RefResolver(base_uri=base_uri, referrer=response_schema)
validator = Draft7Validator(response_schema, resolver=resolver)

validator.validate(data)
```

If I change `"additionalProperties"` to `true` it works, but that means the `$ref` is silently not being resolved. Even changing `$ref` to `file` (or `$file`?) as I did before doesn't work here.

In the documentation, it might be helpful to give an example of the expected format for `base_uri` in the `RefResolver`; I've seen `file://{path}/`, `file:{path}`, `{path}` - I've tried them all!
