### ISSUE TITLE
Custom error message instead of "xx is a required property"

### ISSUE THREAD

**Issue by OrangePJ** [Julian/jsonschema#691] opened 2020-05-25 09:00 UTC
```Python
# This is my schema
schema = {
    "type": "object",
    "properties": {
        "pid": {"type": "integer", "error": (4001, "pid error")},
        "email": {"type": "string", "error": (4002, "email error")},
        ...
    },
    "required": ["pid", "email",  ...]
}


# This is how I process the errors
my_data = {
    "pid": 1,
    "email": "test@test.com"
}
v = Draft7Validator(schema)
err_list = []
for error in v.iter_errors(my_data):
    err_list.append(error.schema["error"])
print(err_list)
```

My requirement is to get all validation errors, so I used `iter_errors` to get them.
But I only can retrieve the `error` field that I defined myself when the `pid` has data but the wrong type. I can not get the custom `error` field if I don't post `pid` in `my_data`.

Does anyone know the resolution? (I must add the custom error message for every field)

**Comment by Julian** [comment] 2020-06-03 13:59
Hi. This sounds like a duplicate of #119. Please have a look there, and certainly a PR is welcome.

**Closed by Julian** 2020-06-03 13:59 UTC
