### ISSUE TITLE
Old versions of pip do not understand environment markers

### ISSUE THREAD

**Issue by tbsf** [Julian/jsonschema#233] opened 2015-06-10 00:11 UTC
In compat.py:

 36     if PY26:
 37         from repoze.lru import lru_cache
 38     else:
 39         from functools32 import lru_cache

in setup.py:

extras_require = {
    "format" : ["rfc3987", "strict-rfc3339", "webcolors"],
    ":python_version=='2.6'": ["argparse", "repoze.lru"],
    ":python_version=='2.7'": ["functools32"],
}

Maybe this should be python_version>=2.7?

**Comment by Julian** [comment] 2015-06-10 00:14
Sorry, I'm not sure I understand what issue is being reported here?

**Comment by thebigspacefuck** [comment] 2015-06-10 00:43
I use pip install with 2.7.5. This doesn't install functools32 automatically, so it fails to import.

**Comment by Julian** [comment] 2015-06-10 01:10
OK, so this isn't related to Python 2.6 or other versions? I was confused by the issue title.

So you're saying that you installed jsonschema into Python 2.7 and didn't get the appropriate dep on `functools32`?

Can you show the output of your pip install, along with versions of pip and setuptools that are being used?

**Comment by wrigri** [comment] 2015-06-10 23:07
Hi Julian,
I'm not the OP, but I can reproduce this. (And it only started occurring with the latest release)

I'm testing this on a Debian 7 virtual machine running on Google Compute Engine.  Here are the commands I ran and their output (Let me know if I can help with additional info):
$ python --version
Python 2.7.3

$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ pip freeze
M2Crypto==0.21.1
PyYAML==3.10
argparse==1.2.1
boto==2.3.0
distribute==0.7.3
euca2ools==2.0.2
gcimagebundle==1.2.6
paramiko==1.7.7.1
pycrypto==2.6
wsgiref==0.1.2

$ sudo pip -v install jsonschema
Downloading/unpacking jsonschema
  Using version 2.5.1 (newest of versions: 2.5.1, 2.5.1, 2.5.0, 2.5.0, 2.4.0, 2.4.0, 2.3.0, 2.3.0, 2.2.0, 2.2.0, 
2.1.0, 2.1.0, 2.0.0, 2.0.0, 1.3.0, 1.3.0, 1.2.0, 1.2.0, 1.1.0, 1.1.0, 1.0.0, 1.0.0, 0.8.0, 0.8.0, 0.7, 0.7, 0.6, 
0.6, 0.5, 0.5, 0.4, 0.4, 0.3, 0.3, 0.2, 0.2, 0.1a)
  Downloading jsonschema-2.5.1.tar.gz (50Kb): 50Kb downloaded
  Running setup.py egg_info for package jsonschema
    zip_safe flag not set; analyzing archive contents...
    
    Installed /home/rickw/build/jsonschema/.eggs/vcversioner-2.14.0.0-py2.7.egg
    running egg_info
    creating pip-egg-info/jsonschema.egg-info
    writing requirements to pip-egg-info/jsonschema.egg-info/requires.txt
    writing pip-egg-info/jsonschema.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/jsonschema.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/jsonschema.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/jsonschema.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/jsonschema.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/jsonschema.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/jsonschema.egg-info/SOURCES.txt'
Installing collected packages: jsonschema
  Running setup.py install for jsonschema
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/_validators.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/_format.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/exceptions.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/__main__.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/_utils.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/_version.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/cli.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/validators.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/compat.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/_reflect.py -> build/lib.linux-x86_64-2.7/jsonschema
    copying jsonschema/__init__.py -> build/lib.linux-x86_64-2.7/jsonschema
    creating build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/test_exceptions.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/test_format.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/test_cli.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/test_jsonschema_test_suite.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/compat.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/__init__.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    copying jsonschema/tests/test_validators.py -> build/lib.linux-x86_64-2.7/jsonschema/tests
    creating build/lib.linux-x86_64-2.7/jsonschema/schemas
    copying jsonschema/schemas/draft4.json -> build/lib.linux-x86_64-2.7/jsonschema/schemas
    copying jsonschema/schemas/draft3.json -> build/lib.linux-x86_64-2.7/jsonschema/schemas
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/jsonschema
    creating /usr/local/lib/python2.7/dist-packages/jsonschema/schemas
    copying build/lib.linux-x86_64-2.7/jsonschema/schemas/draft4.json -> /usr/local/lib/python2.7/dist-packages/jsonschema/schemas
    copying build/lib.linux-x86_64-2.7/jsonschema/schemas/draft3.json -> /usr/local/lib/python2.7/dist-packages/jsonschema/schemas
    copying build/lib.linux-x86_64-2.7/jsonschema/_validators.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/_format.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/exceptions.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/__main__.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/_utils.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/_version.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/cli.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/validators.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    creating /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/test_exceptions.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/test_format.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/test_cli.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/test_jsonschema_test_suite.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/compat.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/__init__.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/tests/test_validators.py -> /usr/local/lib/python2.7/dist-packages/jsonschema/tests
    copying build/lib.linux-x86_64-2.7/jsonschema/compat.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/_reflect.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    copying build/lib.linux-x86_64-2.7/jsonschema/__init__.py -> /usr/local/lib/python2.7/dist-packages/jsonschema
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/_validators.py to _validators.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/_format.py to _format.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/exceptions.py to exceptions.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/__main__.py to __main__.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/_utils.py to _utils.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/_version.py to _version.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/cli.py to cli.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/validators.py to validators.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/test_exceptions.py to test_exceptions.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/test_format.py to test_format.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/test_cli.py to test_cli.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/test_jsonschema_test_suite.py to test_jsonschema_test_suite.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/compat.py to compat.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/__init__.py to __init__.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/tests/test_validators.py to test_validators.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/compat.py to compat.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/_reflect.py to _reflect.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py to __init__.pyc
    running install_egg_info
    running egg_info
    writing requirements to jsonschema.egg-info/requires.txt
    writing jsonschema.egg-info/PKG-INFO
    writing top-level names to jsonschema.egg-info/top_level.txt
    writing dependency_links to jsonschema.egg-info/dependency_links.txt
    writing entry points to jsonschema.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'jsonschema.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'jsonschema.egg-info/SOURCES.txt'
    Copying jsonschema.egg-info to /usr/local/lib/python2.7/dist-packages/jsonschema-2.5.1-py2.7.egg-info
    running install_scripts
    Installing jsonschema script to /usr/local/bin
    writing list of installed files to '/tmp/pip-BcsV4r-record/install-record.txt'
Successfully installed jsonschema
Cleaning up...
  Removing temporary dir /home/rickw/build...

$ python -c 'import jsonschema'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/exceptions.py", line 6, in <module>
    from jsonschema import _utils
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import str_types, MutableMapping, urlsplit
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/compat.py", line 39, in <module>
    from functools32 import lru_cache
ImportError: No module named functools32

$ sudo pip install functools32
Downloading/unpacking functools32
  Downloading functools32-3.2.3-1.tar.gz
  Running setup.py egg_info for package functools32
    /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '3.2.3-1' to '3.2.3.post1'
      normalized_version,
    
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
Installing collected packages: functools32
  Running setup.py install for functools32
    /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '3.2.3-1' to '3.2.3.post1'
      normalized_version,
    
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
Successfully installed functools32
Cleaning up...

$ python -c 'import jsonschema'
$

**Comment by dnephin** [comment] 2015-06-10 23:17
You'll need to use pip >= 6.0 otherwise it doesn't understand the environment markers that are used to tell it to install functools32 (https://pip.pypa.io/en/latest/news.html)

**Comment by wrigri** [comment] 2015-06-10 23:48
Fair enough. This doesn't really cause an issue for us (already fixed the specific problem that it caused on our end), but I noticed the breakage (since we are using pip from the Debian 7 repository), saw this issue and thought I would add some additional info to it.

I can't speak for the OP, of course, but I don't personally need this issue "fixed".

**Comment by asottile** [comment] 2015-09-07 21:51
One slight correction from @dnephin's message above: you'll only need pip>=1.5 (instead of pip>=6)

**Comment by Julian** [comment] 2015-10-02 14:11
I think that the best thing to do here seems like a WONTFIX for better or worse. IME, too many things don't work properly with pip<6 these days anyhow, so users should be "encouraged" to upgrade.

If anyone feels strongly otherwise or wants to discuss further, feel free to follow up.

**Closed by Julian** 2015-10-02 14:11 UTC
Labels: Enhancement
